

###
GET localhost:8082/send?msg=今天重装系统了

<> 2021-05-02T235023.200.txt

###
GET /event

### 请求select接口
GET localhost:8080/sql/select

### 请求insert接口
GET localhost:8080/sql/insert

### 请求insert接口
GET localhost:8080/sql/insertList

### 请求deleteList接口
GET localhost:8080/sql/deleteList